openapi: 3.0.3
info:
  title: Brain Agriculture API
  description: API para gerenciamento de produtores rurais, fazendas e culturas agrícolas
  version: 1.0.0
  contact:
    name: Brain Agriculture Team
    email: contato@brainagriculture.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Servidor de desenvolvimento
  - url: https://api.brainagriculture.com
    description: Servidor de produção

paths:
  /api/producers:
    get:
      summary: Listar produtores
      description: Retorna a lista de todos os produtores cadastrados
      tags:
        - Produtores
      parameters:
        - name: id
          in: query
          description: ID do produtor específico
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Lista de produtores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producer"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Criar produtor
      description: Cria um novo produtor rural
      tags:
        - Produtores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProducerInput"
      responses:
        "201":
          description: Produtor criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producer"
        "400":
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Atualizar produtor
      description: Atualiza um produtor existente
      tags:
        - Produtores
      parameters:
        - name: id
          in: query
          description: ID do produtor
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProducerInput"
      responses:
        "200":
          description: Produtor atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producer"
        "400":
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Produtor não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Excluir produtor
      description: Remove um produtor do sistema
      tags:
        - Produtores
      parameters:
        - name: id
          in: query
          description: ID do produtor
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Produtor excluído com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Producer deleted successfully"
        "400":
          description: ID não fornecido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Produtor não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/dashboard:
    get:
      summary: Estatísticas do dashboard
      description: Retorna estatísticas para o dashboard principal
      tags:
        - Dashboard
      responses:
        "200":
          description: Estatísticas do dashboard
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DashboardStats"
        "500":
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Producer:
      type: object
      properties:
        id:
          type: string
          description: ID único do produtor
          example: "1"
        document:
          type: string
          description: CPF ou CNPJ do produtor
          example: "123.456.789-00"
        name:
          type: string
          description: Nome do produtor
          example: "João Silva"
        farms:
          type: array
          description: Lista de fazendas do produtor
          items:
            $ref: "#/components/schemas/Farm"
      required:
        - id
        - document
        - name
        - farms

    ProducerInput:
      type: object
      properties:
        document:
          type: string
          description: CPF ou CNPJ do produtor
          example: "123.456.789-00"
        name:
          type: string
          description: Nome do produtor
          example: "João Silva"
        farms:
          type: array
          description: Lista de fazendas do produtor
          items:
            $ref: "#/components/schemas/Farm"
      required:
        - document
        - name

    Farm:
      type: object
      properties:
        id:
          type: string
          description: ID único da fazenda
          example: "1"
        name:
          type: string
          description: Nome da fazenda
          example: "Fazenda São João"
        city:
          type: string
          description: Cidade da fazenda
          example: "Ribeirão Preto"
        state:
          type: string
          description: Estado da fazenda
          example: "São Paulo"
        totalArea:
          type: number
          description: Área total em hectares
          example: 500
        arableArea:
          type: number
          description: Área agricultável em hectares
          example: 400
        vegetationArea:
          type: number
          description: Área de vegetação em hectares
          example: 100
        crops:
          type: array
          description: Lista de culturas plantadas
          items:
            $ref: "#/components/schemas/Crop"
      required:
        - id
        - name
        - city
        - state
        - totalArea
        - arableArea
        - vegetationArea
        - crops

    Crop:
      type: object
      properties:
        id:
          type: string
          description: ID único da cultura
          example: "1"
        name:
          type: string
          description: Nome da cultura
          example: "Soja"
        season:
          type: string
          description: Safra da cultura
          example: "Safra 2023"
        hectares:
          type: number
          description: Área plantada em hectares
          example: 300
      required:
        - id
        - name
        - season
        - hectares

    DashboardStats:
      type: object
      properties:
        totalFarms:
          type: integer
          description: Total de fazendas cadastradas
          example: 156
        totalHectares:
          type: number
          description: Total de hectares registrados
          example: 45230
        stateDistribution:
          type: array
          description: Distribuição de fazendas por estado
          items:
            type: object
            properties:
              state:
                type: string
                example: "São Paulo"
              count:
                type: integer
                example: 45
        cropDistribution:
          type: array
          description: Distribuição de culturas por hectares
          items:
            type: object
            properties:
              crop:
                type: string
                example: "Soja"
              hectares:
                type: number
                example: 18500
        landUseDistribution:
          type: array
          description: Distribuição do uso do solo
          items:
            type: object
            properties:
              type:
                type: string
                example: "Área Agricultável"
              hectares:
                type: number
                example: 36184
      required:
        - totalFarms
        - totalHectares
        - stateDistribution
        - cropDistribution
        - landUseDistribution

    Error:
      type: object
      properties:
        error:
          type: string
          description: Mensagem de erro
          example: "Producer not found"
      required:
        - error

tags:
  - name: Produtores
    description: Operações relacionadas aos produtores rurais
  - name: Dashboard
    description: Estatísticas e métricas do sistema
