// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_dashboard from "./routes/api/dashboard.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_producers from "./routes/api/producers.ts";
import * as $farms from "./routes/farms.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $producers from "./routes/producers.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/dashboard.ts": $api_dashboard,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/producers.ts": $api_producers,
    "./routes/farms.tsx": $farms,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/producers.tsx": $producers,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
